language: python

env:
  - PYVERSION=3.6

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda info -a

install:
  - conda create --yes --file ci/requirements.txt -n test-env python=$PYVERSION -c conda-forge -c bioconda
  - conda install -n test-env --yes flake8 nose coveralls
  - source activate test-env
  - pip install -e .

script:
  - source activate test-env
  # setup dummy test data
  # TODO put in a script and make a second simulation
  - mkdir -p data/simulations/test-sim/fake_date_sample_{0,1}/reads/
  - echo '' > data/simulations/test-sim/fake_date_sample_0/reads/anonymous_reads.fq.gz
  - echo '' > data/simulations/test-sim/fake_date_sample_1/reads/anonymous_reads.fq
  - echo '' > data/simulations/test-sim/taxonomic_profile_0.txt
  - echo '' > data/simulations/test-sim/taxonomic_profile_1.txt
  # snakemake dry run
  - snakemake -n -r --configfile ci/config.yaml
  # unit tests
  - nosetests -v benchutils --with-coverage --cover-package=benchutils
  # lint
  - flake8 benchutils/ setup.py

after_success:
  - coveralls
