language: python

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
  - conda info -a

install:
  # python version = 3.6 via envs/snakemake.yml
  - conda env create --file envs/snakemake.yml -n test-env
  - conda install -n test-env --yes flake8 nose coveralls
  - source activate test-env
  - pip install -e .

script:
  - source activate test-env
  # setup dummy test data
  - chmod +x ci/setup_demo_data.sh
  - zsh ci/setup_demo_data.sh
  # snakemake dry run
  - snakemake -n -r --configfile ci/config.yaml
  # unit tests
  - nosetests -v benchutils --with-coverage --cover-package=benchutils
  # lint
  - flake8 benchutils/ setup.py

after_success:
  - coveralls
