kraken_db:
    "/projects/genome_annotation/ref107/dbs/kraken2"
ranks:
    # if not in a list, it will mess up (same for all below)
    ["family", "genus", "species"]
methods:
    ["kraken2", "metaphlan2"] # "shogun"]
metrics:
    ['correlation', 'l2_norm', 'auprc', 'absolute_error']
metric_comparisons1:
    ['l2_norm', 'l2_norm']
metric_comparisons2:
    ['absolute_error', 'auprc']
