kraken2_db:
    "/projects/genome_annotation/ref107/dbs/kraken2"
ranks:
    # if not in a list, it will mess up (same for all below)
    ["genus"]
methods:
    ["kraken2", "metaphlan2", "mohawk"]
metrics:
    ['pearsonr', 'l2_norm', 'l1_norm', 'auprc', 'absolute_error', 'kl_divergence', 'f1',
     'precision', 'recall', 'spearmanr']
metric_comparisons1:
    ['l2_norm', 'l2_norm']
metric_comparisons2:
    ['absolute_error', 'auprc']
mohawk_model:
    "/home/garmstro/gwarmstrong-repos/mohawk/runs/Sep05_16-33-46_brncl-34.ucsd.edu/models/trained_model_epoch_25_seed_1234.mod"

params:
  {
   "kraken2": [
                {"db": "/projects/genome_annotation/ref107/dbs/kraken2"},
                {"db": "/panfs/panfs1.ucsd.edu/panscratch/garmstro/kraken_db/kraken-standard"}
              ],
   "metaphlan2": None,
   "mohawk": [
                {"model": "/home/garmstro/gwarmstrong-repos/mohawk/runs/Sep05_16-33-46_brncl-34.ucsd.edu/models/trained_model_epoch_20_seed_1234.mod"},
                {"model": "/home/garmstro/gwarmstrong-repos/mohawk/runs/Sep05_16-33-46_brncl-34.ucsd.edu/models/trained_model_epoch_25_seed_1234.mod"},
                {"model": "/home/garmstro/gwarmstrong-repos/mohawk/runs/Sep09_12-09-35_brncl-34.ucsd.edu/models/trained_model_epoch_95_seed_1234.mod"},
                {"model": "/home/garmstro/gwarmstrong-repos/mohawk/runs/Sep10_13-48-31_brncl-34.ucsd.edu/models/trained_model_epoch_95_seed_1234.mod"}
             ]
  }
