kraken2_db:
    "/path/to/db"
ranks:
    # if not in a list, it will mess up
    ["genus"]
methods:
  ["kraken2", "metaphlan2", "mohawk"] # "shogun"]
metrics:
  ['pearsonr', 'l2_norm', 'auprc', 'absolute_error']
metric_comparisons1:
  ['l2_norm', 'l2_norm']
metric_comparisons2:
  ['absolute_error', 'auprc']
mohawk_model:
  "ci/test_model.mod"
