kraken2_db:
    "/path/to/db"
ranks:
    # if not in a list, it will mess up
    ["genus"]
methods:
  ["kraken2", "metaphlan2", "mohawk"] # "shogun"]
metrics:
  ['pearsonr', 'l2_norm', 'auprc', 'absolute_error']
metric_comparisons1:
  ['l2_norm', 'l2_norm']
metric_comparisons2:
  ['absolute_error', 'auprc']
mohawk_model:
  "ci/test_model.mod"

params:
  {
    "kraken2": [{"db": "/projects/genome_annotation/ref107/dbs/kraken2"},
                {"db": "/projects/genome_annotation/ref107/dbs/kraken2_alt"}],
    "metaphlan2": None,
    "mohawk": [{"model": "/home/garmstro/gwarmstrong-repos/mohawk/runs/Sep05_16-33-46_brncl-34.ucsd.edu/models/trained_model_epoch_25_seed_1234.mod"}]
  }
